version: "3"
services:
  stream_agent_server:
    image: emiyalee/stream_agent_server:1.0.1
    command: stream_agent_server -consul_host consul
    ports:
      - "11001:8080"
    environment:
      - SERVICE_NAME=stream-agent-service
    deploy:
      replicas: 5
      restart_policy:
        condition: any
    networks: 
      - net_service
      # - log_system_lognet

  play_control_server:
    image: emiyalee/play_control_server:1.0.0
    command: play_control_server -consul_host consul -db_host media_db
    environment:
      - SERVICE_NAME=play-control-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks: 
      - net_service
      # - log_system_lognet

  segment_server:
    image: emiyalee/segment_server:1.0.0
    command: segment_server -consul_host consul
    environment:
      - SERVICE_NAME=segment-service
    deploy:
      replicas: 5
      restart_policy:
        condition: any
    networks: 
      - net_service
      # - log_system_lognet

  store_server:
    image: nginx:1.14.0
    volumes:
      - /home/lihualin/workspace/go/src/github.com/emiyalee/stream_system/deploy/vod/store:/usr/share/nginx/html/store
    # ports:
    #   - "12001:80"
    environment:
      - SERVICE_NAME=store-server
    deploy:
      replicas: 4
      # placement: 
      #   constraints: [node.role == manager]  
    networks: 
      - net_service

  stream_server:
    image: nginx:1.14.0
    volumes:
      - /home/lihualin/workspace/go/src/github.com/emiyalee/stream_system/deploy/vod/stream:/usr/share/nginx/html/stream
      - /home/lihualin/workspace/go/src/github.com/emiyalee/stream_system/deploy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "13001:80"
    environment:
      - SERVICE_NAME=stream-server
    deploy:
      replicas: 4
      # placement: 
      #   constraints: [node.role == manager]  
    networks: 
      - net_service

  media_db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    environment:
      - SERVICE_NAME=media-info-database
    ports:
      - "3306:3306"
    volumes:
      - /home/lihualin/workspace/go/src/github.com/emiyalee/stream_system/deploy/data:/var/lib/mysql
    deploy:
      placement: 
        constraints: [node.role == manager]
    networks: 
      - net_service

  consul:
    image: consul:1.1.0
    ports:
      - "8500:8500"
    command: agent -server -bootstrap -bootstrap-expect=1 -bind=127.0.0.1 -client=0.0.0.0 -ui
    deploy:
      placement: 
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    environment:
      - CONSUL_UI_BETA=1
      - SERVICE_IGNORE=true
    networks: 
      - net_service

  registrator-1:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500 
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    deploy:
      placement:
        constraints: [node.hostname == centos-7-1]
    networks:
      - net_service

  registrator-2:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500 
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    deploy:
      placement:
        constraints: [node.hostname == centos-7-2]
    networks:
      - net_service

networks: 
  net_service:
  # log_system_lognet:
  #   external: true

# volumes:
#   vod-volume:
#     external: true
